fix: multithreaded decompression for larger chunk files
seung-lab/PyChunkedGraph pull request #457
Opened 2023-08-31 18:55 UTC by akhileshh

@ranlu 's tests show  `multi_decompress_to_buffer` significantly improves decompression times for larger files.

2023-08-31 19:10 UTC, ranlu requested changes
`multi_decompress_to_buffer` needs a list of segments and it multi-thread at segment level, so you will not be able to take advantage of multi cores if you feed the files one by one, I think you need to restructure the code to decompress all chunks once to use all the cores.

One potential issue is that `multi_decompress_to_buffer` returns a `BufferWithSegmentsCollection`, I can use it as a list of bytearrays, but I have not tested you can use it directly or wrap it in a memoryview() in your code, if you want to get a realy byte copy it will negate most of the speed up.

2023-09-02 04:56 UTC, ranlu reviewed
Looks reasonable to me. I still hope to avoid the `tobytes()` call which is slow and doubles the memory needed, but do not have time to investigate it now.

2023-09-02 04:56 UTC, ranlu commented on pychunkedgraph/io/edges.py
> +    decompressed = zdc.multi_decompress_to_buffer(compressed, threads=4)
Maybe `threads=-1`  is better, negative number is equivalent to `threads=#vcpu`

2023-09-02 04:56 UTC, ranlu commented on pychunkedgraph/io/edges.py
> +    cf = CloudFiles(edges_dir, num_threads=4)
This is not exactly about multi-thread decompression so kind of off-topic, but I do not mind to have it since this speeds things up.

2023-09-02 18:02 UTC, ranlu commented
I feel the best solution is to upgrade to protobuf >= 4.22, then we do not even need the explicit memoryview call. 
Also a potential risk of `multi_decompress_to_buffer` is that it is ```Experimental. Not available in CFFI backend.```. I think this at least means it is not available in pypy, and zstandard installed through conda.

2023-09-04 05:26 UTC, ranlu commented
Actually no version of protobuf I installed from pypi worked without memoryview, probably due to https://github.com/protocolbuffers/protobuf/issues/10774. I suppose the best compromise is to use pure python backend by setting `export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`. This is still almost 2x faster than making the copy or adding memoryview.
protobuf packaged by conda still using the "deprecated" `cpp` backend also works fine, and gives another 2x faster than the python backend.

2023-09-07 01:56 UTC, ranlu commented
I created a [Dockerfile](https://gist.github.com/ranlu/5a09f51afe039643d932dfc08056c4c5) to revert commt b19c81 in protobuf and build the wheel file for python 3.11. It is faster than the python backend, also use far less memory: for 2GB of input python backend used another 3GB memory, upb used almost no extra memory . This can be add to the multi-stage dockerfile @nkemnitz suggested in https://github.com/seung-lab/PyChunkedGraph/pull/406

2023-09-14 05:08 UTC, ranlu commented on pychunkedgraph/io/edges.py
> +    decompressed = zdc.multi_decompress_to_buffer(compressed, threads=-1)
We discussed today and @sdorkenw want to have the number of threads configurable, @akhileshh, maybe read the number of thread from a env so we can control it at deployment time?

2023-09-16 02:19 UTC, ranlu commented
LGTM, I suppose you need to add the environment variables (`PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION` and `ZSTD_THREADS`) to the deployment repo, correct?

2023-09-16 03:05 UTC, akhileshh commented
Yeah that's correct, will be taken care of in [CAVEdeployment](https://github.com/seung-lab/CAVEdeployment).

2023-09-20 10:57 UTC, fcollman commented
I have the changes now in CAVEdeployment, @ranlu @akhileshh.  I'm going to rebase this branch and test it on our test deployment

2023-09-20 11:08 UTC, fcollman commented
This worked fine on our test deployment, so I think we are good to merge this

2023-09-20 15:59 UTC, merged